x-shared:
  zammad-service: &zammad-service
    environment: &zammad-environment
      MEMCACHE_SERVERS: ${MEMCACHE_SERVERS:-zammad-memcached:11211}
      POSTGRESQL_DB: ${POSTGRES_DB:-zammad_production}
      POSTGRESQL_HOST: ${POSTGRES_HOST:-zammad-postgresql}
      POSTGRESQL_USER: ${POSTGRES_USER:-zammad}
      POSTGRESQL_PASS: ${POSTGRES_PASS:-zammad}
      POSTGRESQL_PORT: ${POSTGRES_PORT:-5432}
      POSTGRESQL_OPTIONS: ${POSTGRESQL_OPTIONS:-?pool=50}
      POSTGRESQL_DB_CREATE:
      REDIS_URL: ${REDIS_URL:-redis://zammad-redis:6379}
      S3_URL:
      # Backup settings
      BACKUP_DIR: "${BACKUP_DIR:-/var/tmp/zammad}"
      BACKUP_TIME: "${BACKUP_TIME:-03:00}"
      HOLD_DAYS: "${HOLD_DAYS:-10}"
      TZ: "${TZ:-Europe/Bratislava}"
      # Allow passing in these variables via .env:
      AUTOWIZARD_JSON:
      AUTOWIZARD_RELATIVE_PATH:
      ELASTICSEARCH_USER: ${ELASTICSEARCH_USER:-ops-triage-zammad}
      ELASTICSEARCH_PASS: ${ELASTICSEARCH_PASS:-zammadpass}
      NGINX_PORT:
      NGINX_CLIENT_MAX_BODY_SIZE: "100M"
      NGINX_SERVER_NAME:
      NGINX_SERVER_SCHEME:
      RAILS_TRUSTED_PROXIES:
      ZAMMAD_HTTP_TYPE:
      ZAMMAD_FQDN:
      ZAMMAD_WEB_CONCURRENCY:
      ZAMMAD_SESSION_JOBS_CONCURRENT:
      ZAMMAD_PROCESS_SCHEDULED_JOBS_WORKERS:
      ZAMMAD_PROCESS_DELAYED_JOBS_WORKERS:
      # Variables used by ngingx-proxy container for reverse proxy creations
      # for docs refer to https://github.com/nginx-proxy/nginx-proxy
      VIRTUAL_HOST:
      VIRTUAL_PORT:
      # Variables used by acme-companion for retrieval of LetsEncrypt certificate
      # for docs refer to https://github.com/nginx-proxy/acme-companion
      LETSENCRYPT_HOST:
      LETSENCRYPT_EMAIL:
      # custom ENVS

    env_file:
      - path: .env.sample
        required: false
      - path: .env
        required: false

    extra_hosts:
      - host.docker.internal:host-gateway

    build: .

    volumes:
      - zammad-storage:/opt/zammad/storage
    depends_on:
      - zammad-memcached
      - zammad-postgresql
      - zammad-redis

services:
#  zammad-backup:
#    <<: *zammad-service
#    command: ["zammad-backup"]
#    volumes:
#      - zammad-backup:/var/tmp/zammad
#      - zammad-storage:/opt/zammad/storage:ro
#    user: 0:0

  # zammad-elasticsearch:
  #   build:
  #     context: elasticsearch
  #     dockerfile: Dockerfile
  #   restart: always
  #   volumes:
  #     - elasticsearch-data:/usr/share/elasticsearch/data
  #   environment:
  #     discovery.type: single-node
  #     xpack.security.enabled: true
  #     ES_JAVA_OPTS: "-Xms1g -Xmx1g"
  #     ELASTIC_PASSWORD: ${ELASTIC_PASSWORD:-elasticpass}
  #   deploy:
  #     resources:
  #       limits:
  #         memory: 4g

  # zammad-init-elastic-users:
  #   build:
  #     context: elasticsearch
  #     dockerfile: Dockerfile
  #   depends_on:
  #     - zammad-elasticsearch
  #   entrypoint: sh /tmp/ops_scripts/init_kibana_and_triage_users.sh
  #   environment:
  #     ELASTICSEARCH_SCHEMA: ${ELASTICSEARCH_SCHEMA:-http}
  #     ELASTICSEARCH_HOST: ${ELASTICSEARCH_HOST:-zammad-elasticsearch}
  #     ELASTICSEARCH_PORT: ${ELASTICSEARCH_PORT:-9200}
  #     ELASTICSEARCH_USER: ${ELASTICSEARCH_USER:-ops-triage-zammad}
  #     ELASTICSEARCH_PASS: ${ELASTICSEARCH_PASS:-zammadpass}
  #     ELASTIC_PASSWORD: ${ELASTIC_PASSWORD:-elasticpass}
  #     KIBANA_PASSWORD: ${KIBANA_PASSWORD:-kibanapass}

  # zammad-kibana:
  #   image: kibana:8.17.3
  #   restart: always
  #   volumes:
  #     - kibana-data:/usr/share/kibana/data
  #   environment:
  #     ELASTICSEARCH_HOSTS: http://zammad-elasticsearch:9200
  #     ELASTICSEARCH_USERNAME: kibana_system
  #     ELASTICSEARCH_PASSWORD: ${KIBANA_PASSWORD:-kibanapass}
  #   depends_on:
  #     - zammad-elasticsearch
  #   ports:
  #     - "5601:5601"

  zammad-init:
    <<: *zammad-service
    command: ["zammad-init"]
    depends_on:
      - zammad-postgresql
    restart: on-failure
    user: 0:0

  zammad-memcached:
    command: memcached -m 256M
    image: memcached:${MEMCACHE_VERSION:-1.6.37-alpine}
    restart: ${RESTART:-always}

  zammad-nginx:
    <<: *zammad-service
    command: ["zammad-nginx"]
    expose:
      - "${NGINX_PORT:-8080}"
    ports:
      - "${NGINX_EXPOSE_PORT:-8080}:${NGINX_PORT:-8080}"
    depends_on:
      - zammad-railsserver

  zammad-postgresql:
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-zammad_production}
      POSTGRES_USER: ${POSTGRES_USER:-zammad}
      POSTGRES_PASSWORD: ${POSTGRES_PASS:-zammad}
    image: postgres:${POSTGRES_VERSION:-17.4-alpine}
    restart: ${RESTART:-always}
    volumes:
      - postgresql-data:/var/lib/postgresql/data

  zammad-railsserver:
    <<: *zammad-service
    command: ["zammad-railsserver"]

  zammad-redis:
    image: redis:${REDIS_VERSION:-7.4.2-alpine}
    restart: ${RESTART:-always}
    volumes:
      - redis-data:/data

  zammad-scheduler:
    <<: *zammad-service
    command: ["zammad-scheduler"]

  zammad-websocket:
    <<: *zammad-service
    command: ["zammad-websocket"]

volumes:
  elasticsearch-data:
    driver: local
  kibana-data:
    driver: local
  postgresql-data:
    driver: local
  redis-data:
    driver: local
  zammad-backup:
    driver: local
  zammad-storage:
    driver: local
