servers:
  web:
    hosts:
      - 88.99.99.215
    proxy:
      host: triaz.odkazprestarostu.sk
    options:
      memory: 4g

  websocket:
    hosts:
      - 88.99.99.215

  worker:
    hosts:
      - 88.99.99.215

proxy:
  host: triaz.odkazprestarostu.sk

env:
  clear:
    WEB_CONCURRENCY: 8
    MAX_THREADS: 15

    OPS_PORTAL_URL: https://novy.odkazprestarostu.sk
    OPS_PORTAL_PUBLIC_URL: https://novy.odkazprestarostu.sk
    FQDN: triaz.odkazprestarostu.sk
    PRODUCT_NAME: Triáž
    ORGANIZATION: Odkaz pre starostu
    ADMIN_EMAIL: <%= ENV.fetch('ADMIN_EMAIL', 'example@example.org') %>
    ADMIN_FIRSTNAME: Superadmin
    ADMIN_LASTNAME: User
    OTHER_RESPONSIBLE_SUBJECT_ID: 410
    Z_LOCALES: "sk:en-us"

    POSTGRESQL_DB: ops_triage_zammad_production
    POSTGRESQL_HOST: host.docker.internal
    POSTGRESQL_USER: ops_triage_zammad
    POSTGRESQL_OPTIONS: "?pool=100"

accessories:
  elastic:
    env:
      clear:
        ES_JAVA_OPTS: "-Xms1024m -Xmx1024m"
    options:
      memory: 4g

ssh:
  user: kamal
