name: Deploy accessories to DEV

on:
  workflow_dispatch:

jobs:
  dev-deploy:
    runs-on: ubuntu-latest
    environment: DEV

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: .ruby-version
          bundler-cache: true

      - name: Install Kamal gem
        run: |
          KAMAL_VERSION=$(ruby -rbundler -e "puts Bundler.locked_gems.specs.find { |s| s.name == 'kamal' }&.version")
          gem install kamal -v $KAMAL_VERSION
  
      - uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.DEV_DEPLOY_KEY }}

      - name: Deploy accessories
        env:
          KAMAL_REGISTRY_USERNAME: ${{ secrets.KAMAL_REGISTRY_USERNAME }}
          KAMAL_REGISTRY_PASSWORD: ${{ secrets.KAMAL_REGISTRY_PASSWORD }}
          ELASTIC_PASSWORD: ${{ secrets.ELASTIC_PASSWORD }}
          KIBANA_PASSWORD: ${{ secrets.KIBANA_PASSWORD }}
          ELASTICSEARCH_PASS: ${{ secrets.ELASTICSEARCH_PASS }}
          ELASTICSEARCH_USER: ${{ vars.ELASTICSEARCH_USER }}

        run: |
          kamal accessory reboot redis -d staging
          kamal accessory reboot elastic -d staging
          kamal elastic_init_users -d staging
          kamal accessory reboot kibana -d staging
