name: Deploy to DEV

on:
  workflow_call:
  workflow_dispatch:

jobs:
  dev-deploy:
    runs-on: ubuntu-latest
    environment: DEV

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: .ruby-version
          bundler-cache: true

      - name: Install Kamal gem
        run: |
          KAMAL_VERSION=$(ruby -rbundler -e "puts Bundler.locked_gems.specs.find { |s| s.name == 'kamal' }&.version")
          gem install kamal -v $KAMAL_VERSION
  
      - uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.DEV_DEPLOY_KEY }}

      - name: Run deploy command
        env:
          KAMAL_REGISTRY_USERNAME: ${{ secrets.KAMAL_REGISTRY_USERNAME }}
          KAMAL_REGISTRY_PASSWORD: ${{ secrets.KAMAL_REGISTRY_PASSWORD }}
          ADMIN_PASSWORD: ${{ secrets.ADMIN_PASSWORD }}
          API_TOKEN: ${{ secrets.API_TOKEN }}
          GOOGLE_OAUTH2_CLIENT_ID: ${{ secrets.GOOGLE_OAUTH2_CLIENT_ID }}
          GOOGLE_OAUTH2_CLIENT_SECRET: ${{ secrets.GOOGLE_OAUTH2_CLIENT_SECRET }}
          POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
          RAILS_MASTER_KEY: ${{ secrets.RAILS_MASTER_KEY }}
          WEBHOOK_SECRET: ${{ secrets.WEBHOOK_SECRET }}
          ELASTICSEARCH_PASS: ${{ secrets.ELASTICSEARCH_PASS }}
          ADMIN_EMAIL: ${{ vars.ADMIN_EMAIL }}
          RAILS_LOG_LEVEL: ${{ vars.RAILS_LOG_LEVEL }}
          S3_URL: ${{ secrets.S3_URL }}

        run: |
          kamal deploy -d staging
          kamal accessory reboot railsserver -d staging
          kamal accessory reboot websocket -d staging
