name: Deploy accessories to PROD

on:
  workflow_dispatch:

jobs:
  prod-deploy:
    runs-on: ubuntu-latest
    environment: PROD

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to Dev Container Registry
        uses: docker/login-action@v3
        with:
          registry: registry.dev.slovensko.digital
          username: ${{ secrets.KAMAL_REGISTRY_USERNAME }}
          password: ${{ secrets.KAMAL_REGISTRY_PASSWORD }}

      - name: Build custom ElasticSearch image
        run: |
          docker build -t registry.dev.slovensko.digital/custom-elasticsearch:latest elasticsearch/
          docker push registry.dev.slovensko.digital/custom-elasticsearch:latest

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: .ruby-version
          bundler-cache: true

      - name: Install Kamal gem
        run: |
          KAMAL_VERSION=$(ruby -rbundler -e "puts Bundler.locked_gems.specs.find { |s| s.name == 'kamal' }&.version")
          gem install kamal -v $KAMAL_VERSION
  
      - uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.OPS_PROD_DEPLOY_KEY }}

      - name: Deploy accessories
        env:
          KAMAL_REGISTRY_USERNAME: ${{ secrets.KAMAL_REGISTRY_USERNAME }}
          KAMAL_REGISTRY_PASSWORD: ${{ secrets.KAMAL_REGISTRY_PASSWORD }}
          ELASTIC_PASSWORD: ${{ secrets.ELASTIC_PASSWORD }}
          KIBANA_PASSWORD: ${{ secrets.KIBANA_PASSWORD }}
          ELASTICSEARCH_PASS: ${{ secrets.ELASTICSEARCH_PASS }}

        run: |
          kamal accessory reboot redis -d production
          kamal accessory reboot elastic -d production
          kamal elastic_init_users -d production

